### ISSUE TITLE
Tasks todo

### ISSUE THREAD

**Issue by lukasvdberk** [lukasvdberk/install-it#1]
TODO's for the first version of the project

- [x] Working happy flow
- [x] README.md
- [x] Add end to end tests with cypress 
- [x] Deploy application
- [x] Show error page
- [x] Make responsive and mobile friendly  
   - [x] Home page
   - [x] Package search page
   - [x] Generate script page  
- [x] Add button to inform issues
- [x] Add favicon
